services:
  knowledgebase: 
    build: .
    volumes:
      - kb:/kb

  rickview:
    image: ghcr.io/konradhoeffner/rickview:master
    volumes:
      - kb:/kb:ro
      - ./rickview/data:/app/data:ro
    environment:
      - RICKVIEW_KB_FILE=/kb/lscomplete2015.hdt.zst
      - RICKVIEW_PREFIX=ls
      - RICKVIEW_NAMESPACE=http://linkedspending.aksw.org/
      - RICKVIEW_TITLE=LinkedSpending
      - RICKVIEW_SUBTITLE=Government spendings from all over the world as Linked Data
      - RICKVIEW_EXAMPLES=instance/finland-aid
      - RICKVIEW_GITHUB=https://github.com/konradhoeffner/linkedspending
      - RICKVIEW_DOC=https://nbn-resolving.org/urn:nbn:de:bsz:15-qucosa2-742429
      - RICKVIEW_LARGE=true
      - RICKVIEW_LOG_LEVEL=debug
      - CARGO_INCREMENTAL=0
    ports:
      - "${RICKVIEW_PORT:-127.0.0.1:8080}:8080"
    #restart: unless-stopped

# requires ./data/linkedspending.nt to be available on the host
  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.7
    environment:
      - DBA_PASSWORD=${DBA_PASSWORD}
      - VIRT_DATABASE_ERRORLOGLEVEL=3
      - VIRT_PARAMETERS_NUMBEROFBUFFERS=10000
      - VIRT_PARAMETERS_MAXDIRTYBUFFERS=6000
      - VIRT_HTTPSERVER_SERVERPORT=8890
      - VIRT_SPARQL_DEFAULTGRAPH=http://linkedspending.aksw.org
      - VIRT_SPARQL_RESULTSETMAXROWS=50000
      - VIRT_SPARQL_MAXQUERYCOSTESTIMATIONTIME=400
      - VIRT_SPARQL_MAXQUERYEXECUTIONTIME=120
      - VIRT_SPARQL_DEFAULTQUERY=select distinct * {?s a qb:DataSet.} LIMIT 100
      - VIRT_PLUGINS_-=-
    volumes:
      - ./virtuoso:/opt/virtuoso-opensource/initdb.d:ro
      - ./toload:/database/toload:ro
      - virtuoso-data:/database/data
    profiles: ["virtuoso"]
    ports:
      - "127.0.0.1:8890:8890"
      - "127.0.0.1:1111:1111"
    restart: unless-stopped

volumes:
  kb:
  virtuoso-data:
